# Initially based on https://jekyllrb.com/docs/continuous-integration/travis-ci/

language: python
python:
  - "3.6"

script:
   - ls -lR running-challenges-data/data

# Note, tags are the same as branches when it comes to Travis
branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build
