
# based on https://jekyllrb.com/docs/continuous-integration/travis-ci/


language: ruby
rvm: 2.3.3

env:
  - EXTENSION_BUILD_ID=$TRAVIS_BUILD_ID

before_script:
 - chmod +x ./build/website/build.sh
 - chmod +x ./build/website/build-staging.sh
 - chmod +x ./build/extension-chrome/build.sh
 - chmod +x ./build/extension-firefox/build.sh
 - npm install -g web-ext

script:
   # - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./build/website/build-staging.sh; fi'
   # - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/website/build.sh; fi'
   - './build/extension-chrome/build.sh'
   - './build/extension-firefox/build.sh'

# branch whitelist, only for GitHub Pages - we push raw code to master,
# the build code goes to gh-pages
# Tags are the same as branches when it comes to Travis, so we need to include
# our release tag names here too
branches:
  only:
  - master
  - /^v[0-9]/

before_deploy:
  # Rename the output files to be suitable for uploading to the GitHub release
  - sh -c 'cd ./browser-extensions/chrome/build/web-ext-artifacts && rename 's/^/chrome-/' *.zip'
  - sh -c 'cd ./browser-extensions/firefox/build/web-ext-artifacts && rename 's/^/firefox-/' *.zip'

deploy:
  provider: releases
  name: Running Challenges $TRAVIS_TAG
  api_key:
    secure: er8ZX95bSo7dPDJSYnltMbnhPiTjrUZqw9z/aMo4onGblanoFPug5dvdFWukJy8EYu34o/6XwuApvKyWt29j2J8qkCp8dL1SspCg0dhrrt/bgVuVrWXpKQUj946Hjtn3VU2o81macpCeWE9vg5tRjBaLRtuAeKgzrIfgcS4DymM26n0mL0hTECUTDQHHCPSVycTJ/xDjwxCItwSmeKP3/13GTQHkHEAQKAJ5KqPUjWCTc9/Jbxty0HEKRq/B/NPK3/LlB7PdIMPsdYEiUygUIlUBqAeRVPojeNa1h0u09EtApbUPOo2N5gaxbSy1L3gkdp+smilW6RcyZxoggFx8QrkosGpPU34X4k8wXePQn5mrxK6WXRWpn9uWcCzQKQngLKURz/ktBzAzrdtz8iIkyq0gcqtJ5QF6dhPs0Xy93zqkN/GfBlM+l8XfgE63HLReaKknwDAoyusF3ebM8euTVJGVwqptRuU3m50/YJo1RbGYErL8/9MwpTXnFP2p7MS94lYQmYV4eeiQu5tkC0ZhTvjLU8EXh/9G0naLQZ4DB3NIXI4zI0nXzD5qa4v9TQNjVTCHenjLzqI7SB7FBOX7nCkL3K9ugVtYJ5YxdfkCSxuoeICx/J+WQ5ISSkMvnZg9CQqyGyaHG0TiaobzQTYBTwXMyHr/tgp1OwrLZlLR9es=
  file_glob: true
  file:
    - browser-extensions/chrome/build/web-ext-artifacts/chrome-running_challenges*.zip
    - browser-extensions/firefox/build/web-ext-artifacts/firefox-running_challenges*.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v
    repo: fraz3alpha/travis-testing

sudo: false # route your build to the container-based infrastructure for a faster build
